### ISSUE TITLE
bench: Document that server should be restarted after a bandwidth test

### ISSUE THREAD

**Issue by lziest** [cloudflare/gokeyless#172]
It appears to me that either `bench` tool didn't handle the connection closure (unlikely?) or the server can't handle too many new connections. But it is weird that server only hangs when `bench` tool ran the 2nd time.

**Comment by joshlf** [comment]
From an offline conversation, it seems that this is only an issue when `bench` is run with the `-bandwidth` flag, which performs a bandwidth test rather than a latency test. The bandwidth test sends requests as fast as it can and records the rate and which responses are returned. Since requests can be issued much faster than they can be handled, it's likely that after the bandwidth test finishes, the server still has a very large number of requests queued that it will still try to process.

Without changing the design of the server, this is unavoidable. It should, however, be documented.

**Comment by lziest** [comment]
this seems to go away by itself.
