### ISSUE TITLE
Initialization silently overwrites existing key/cert

### ISSUE THREAD

**Issue by elithrar** [cloudflare/gokeyless#46]
Ref: https://github.com/cloudflare/gokeyless/blob/master/cmd/gokeyless/gokeyless.go#L53-L56

When `NewServerFromFile` fails (e.g. `server.pem` isn't ready, or other files aren't readable), it falls back to the initialization process. This in turn generates a new key and CSR, invalidating any previous certificates, or CSRs (if activating manually).

We should instead consider either prompting, or bailing out unless a flag is passed to allow this.

**Comment by kisom** [comment]
It would probably be useful to check whether any of the files are available, and if they are, the server should probably not generate a new key and CSR.

**Comment by jacobhaven** [comment]
This was intentional. The server attempts to create a TLS listener with the given cert/key file. If they are invalid for any reason (have invalid read permissions, **cert has expired**, etc.), it automatically overwrites them with a newly generated cert/key pair.

It might make sense to not overwrite the key until a matching cert has been generated (though, this would break the "manual" CSR process)

**Comment by elithrar** [comment]
@jacobhaven Which definitely makes sense.

In order to accommodate the manual workflow, we could save the CSR to disk (as well as write it to logs, if we need to) when `-manual-activation` is passed.

On server startup, if the CSR exists on disk, we bail out - "cannot start: existing CSR <filename> in <directory>". 

Users following the manual activation (which should be a rare occurrence) can just delete the CSR once they install `server.pem`, or delete it and re-run the process if they want to start over and trash the key.

**Comment by kisom** [comment]
Closed by #55.
